- name: System setup
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    user: "{{ ansible_user_id }}"
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      become_user: root

    - name: Activate minimize to dock
      shell: gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'

    - name: Install generic packages
      ansible.builtin.apt:
        name:
          - zsh
          - xclip
          - cmake
          - make
          - ninja-build
          - python3-pip
        state: present

    - name: Install generic packages with snap
      community.general.snap:
        name:
          - keepassxc

    - name: Install pre-built neovim
      become_user: root
      shell: |
        curl -SLJO https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
        chmod u+x nvim.appimage
        mv nvim.appimage /usr/local/bin/nvim

    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust
    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Install "ripgrep" Rust package with locked dependencies
      community.general.cargo:
        name: ripgrep
        locked: true

    - name: Install "find (fd)" Rust package with locked dependencies
      community.general.cargo:
        name: fd-find
        locked: true

    - name: Install "eza" Rust package with locked dependencies
      community.general.cargo:
        name: eza
        locked: true

    - name: Install "bat" Rust package with locked dependencies
      community.general.cargo:
        name: bat
        locked: true
